### ISSUE TITLE
Singnature value is getting empty value

### ISSUE THREAD

**Issue by merbin2012** [mobilino/Phonegap-android-license-plugin#4]
Successfully I am getting json response, there I found "responsecode", "signeddata" and "signature" but the signature property values is empty, what is the mean? I am not download this app from playstore but I generate the released apk from android studio (Generate signed APK) option. Is it will get, if I put it into playstore?

**Comment by mobilino** [comment]
Hi Merbin,
to really test the license verification you need to upload your app to the play store as an alpha version. You can add only yourself as a tester if you want to stay private.
/Christof

**Comment by merbin2012** [comment]
Now I am getting signature value randomly, then how can I check is the user license is valid or not?
Don't I need to compare with google play license key?
![license key for app](https://cloud.githubusercontent.com/assets/3687184/19111077/3d7da4e4-8b1b-11e6-9b52-812937d4ba60.jpg)

**Comment by mobilino** [comment]
Hi Merbin,
as stated in the readme this plugin only extracts the license information. This is useful if you want to validate the license information on your server. (Which is much more secure then validating it in the app itself.) Since there is no coding to validate the license information in the app itself, there is also no need to ship your public key as part of the app. 
If you app does not communicate with a server this plugin is not suitable for you.
Regards,
Christof

**Comment by merbin2012** [comment]
Do you know how to check the license key for paid app? (Protect the paid app sharing to another)

**Comment by mobilino** [comment]
You could write a similar plugin and include google's full lvl java example code. I basically removed the validation part. However, this would only stop uninformed users from copying the app since it would be very easy to remove the license verification.
